on:
  workflow_dispatch:
    inputs:
      rid:
        description: 'Release ID'
        required: true
        type: string

jobs:
  job-name:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ inputs.rid }}/assets?name=example.zip" \
            --data-binary "@example.zip"
